apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}-postgresql
  labels:
    {{- include "logto.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database