{{- if .Values.secretExtractor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logto.fullname" . }}-secret-extractor
  labels:
    {{- include "logto.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret-extractor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "logto.fullname" . }}-secret-extractor
  labels:
    {{- include "logto.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret-extractor
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "logto.fullname" . }}-secret-extractor
  labels:
    {{- include "logto.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret-extractor
subjects:
  - kind: ServiceAccount
    name: {{ include "logto.fullname" . }}-secret-extractor
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "logto.fullname" . }}-secret-extractor
  apiGroup: rbac.authorization.k8s.io
{{- end }}
