{{- if .Values.secretExtractor.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "logto.fullname" . }}-secret-extractor-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        {{- include "logto.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: secret-extractor
    spec:
      serviceAccountName: {{ include "logto.fullname" . }}-secret-extractor
      restartPolicy: OnFailure
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: secret-extractor
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          env:
            - name: POSTGRES_HOST
              value: {{ include "logto.fullname" . }}-postgresql
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
          volumeMounts:
            - name: shared-data
              mountPath: /shared
          command:
            - /bin/sh
            - -c
            - |
              # Wait for PostgreSQL to be ready
              until PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1;" > /dev/null 2>&1; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 2
              done

              # Wait for both applications to exist and extract their secrets
              while true; do
                # Check if both applications exist and get their secrets
                SECRETS=$(PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -t -A -F"," -c \
                  "SELECT id, secret FROM applications WHERE id IN ('m-default', 'm-admin');")
                
                COUNT=$(echo "$SECRETS" | wc -l)
                if [ "$COUNT" -eq 2 ]; then
                  echo "Found both applications, extracting secrets..."
                  break
                fi
                
                echo "Waiting for applications to be created..."
                sleep 5
              done

              # Extract and base64 encode secrets
              M_DEFAULT_SECRET=$(echo "$SECRETS" | grep "^m-default," | cut -d',' -f2 | base64)
              M_ADMIN_SECRET=$(echo "$SECRETS" | grep "^m-admin," | cut -d',' -f2 | base64)

              # Create Kubernetes Secret manifest
              cat <<EOF > /shared/secret.yaml
              apiVersion: v1
              kind: Secret
              metadata:
                name: {{ include "logto.fullname" . }}-application-secrets
                labels:
                  {{- include "logto.labels" . | nindent 18 }}
              type: Opaque
              data:
                m-default-secret: $M_DEFAULT_SECRET
                m-admin-secret: $M_ADMIN_SECRET
              EOF

              # Signal that the secret file is ready
              touch /shared/secret-ready

              # Wait for the secret to be applied
              while [ -f /shared/secret-ready ]; do
                sleep 1
              done
        - name: kubectl
          image: "bitnami/kubectl:1.25"
          volumeMounts:
            - name: shared-data
              mountPath: /shared
          command:
            - /bin/sh
            - -c
            - |
              # Wait for the secret file to be ready
              while [ ! -f /shared/secret-ready ]; do
                sleep 1
              done

              # Apply the secret
              kubectl apply -f /shared/secret.yaml

              # Signal completion
              rm -f /shared/secret-ready
{{- end }}
